# Generated by Django 5.1 on 2024-11-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.PositiveIntegerField()),
                ('id_producto', models.PositiveIntegerField()),
                ('id_servicio', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('entrega', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('direccion_envio', models.CharField(max_length=50)),
            ],
        ),
    ]
