# Generated by Django 5.1 on 2024-11-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('id_admin', models.PositiveIntegerField()),
            ],
        ),
    ]
