# Generated by Django 5.1.1 on 2024-11-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id_distribuidor', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('id_producto', models.PositiveIntegerField()),
                ('descuento', models.CharField(max_length=30)),
                ('ciudad_estado', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
                ('telefono', models.PositiveIntegerField()),
            ],
        ),
    ]
